### ISSUE TITLE
Ridge-Regression-Decoder

### ISSUE THREAD

**Issue by KisaragiDev** [kisaragiRY/decoding-DG#3]
* [x] create a make_design_matrix function using spike history
* [x] add verbs to functions in `func.py`
* [x] change `analysis_decoder.ipynb` name-> `analysis_ridge.ipynb`

## Implement the Ridge decoder with cross validation
* [ ] with `design_matrix` using **all neurons** + a range of penalty $\lambda:$ $2^3$ ~ $2^{12}$
* [ ] with `design_matrix_hist` using **some neurons** + a range of penalty $\lambda:$ $2^3$ ~ $2^{12}$
   * there is **a need to reduce the number of neurons** because adding history bins increases the dimensions of design matrix.
      * use mutual information to rank neurons #5  
* [ ] with `design_matrix` using **some neurons** selected above + a range of penalty $\lambda:$ $2^3$ ~ $2^{12}$

## Analyze the results:
1.  Get MAE from models above
2. Run hypothetical test
   * [x] over-all test to see whether the model is okay
   * [x] individual test to see what are the neurons are working

 ---
   *  Take those neurons proved to be **significant** to #4  for analyzing the relationships between the neurons
   *  Do the same thing above for `Lasso decoder`

**Comment by kisaragiRY** [comment]
* [ ] create a make_design_matrix function using spike history
* [ ] add verbs to functions in `func.py`
* [ ] change `analysis_decoder.ipynb` name-> `analysis_ridge.ipynb`

**Comment by KisaragiDev** [comment]
## Encountered importing issues 
`ModuleNotFoundError: No module named 'modules'` in `modules/examples/ridge_regression.py`
1. check whether the working root directory is in the `$PYTHONPATH`
```bash
echo $PYTHONPATH 
```
2. add the root directory to `$PYTHONPATH`
```bash
export PYTHONPATH="$PYTHONPATH:[the root dir]"
```
##  Encountered importing issues 
`ModuleNotFoundError: No module named 'func'` in `modules/decoder.py`
1. use relative import `from .func import *` instead of `from func import *`

**Comment by KisaragiDev** [comment]
# 参考
## time series cross validation

1. [Rolling origin](https://openforecast.org/adam/rollingOrigin.html)
2. [Time series cross-validation](https://otexts.com/fpp3/tscv.html)
