### ISSUE TITLE
Mutual-Infomation

### ISSUE THREAD

**Issue by KisaragiDev** [kisaragiRY/decoding-DG#5]
* [x] create a InfoMetrics class in a new file
* [x] calculate MI and save the results 
* [x] observe how MI changes with the partition methods
* [x] analyze results for both vertical and horizontal partition methods.
---
* [ ] select the neurons with high MI to fit a ridge regression in #3

**Comment by kisaragiRY** [comment]
* [ ] observe how MI changes with the partition methods
